# Hailey Stahl

In [86]:
import numpy as np

# 2. Array of 10 zeros

In [87]:
array10 = np.zeros(10)
print(array10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3. Array of 10 ones

In [88]:
arrayones = np.ones(10)
print(arrayones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# 4. Array of 10 fives

In [89]:
arrayfives = np.ones(10)*5
print(arrayfives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5. Array of integers from 10-50

In [90]:
np.random.randint(10,50,10)

array([26, 16, 30, 32, 19, 16, 49, 20, 18, 16])

# 6.Array of even integers from 10-50

In [91]:
arrayeven = np.arange(10,50,2)
print(arrayeven)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


# 7. 3X3 Matrix with values ranging from 0-8

In [92]:
values = np.random.randint(0,8,9)

matrix = np.array(values).reshape(3,3)
print(matrix)

[[4 3 2]
 [7 1 0]
 [1 0 6]]


 # 8. random number between 0-1

In [93]:
randomnum = np.random.rand(1)
print(randomnum)

[0.28432379]


# 9. Create a matrix using the following statements and display 

In [94]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# a) Get the sum of all the values in the mat matrix


In [95]:
print(mat.sum())

325


# b) Get the standard deviation of the values in the mat matrix


In [96]:
print(round(mat.std(),2))

7.21


# c) Create a new matrix of 25 ones named mat1


In [97]:
mat1= np.ones(25).reshape(5,5)
print(mat1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


 # d) Add the values of mat to those of mat1


In [98]:
add = mat+mat1
print(add)

[[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26.]]


 # e) Multiply the values of mat to those of mat1

In [99]:
multiply = mat*mat1
print(multiply)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
